development:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DATABASE'] %>
  pool: 5
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['TEST_DB'] %>
  pool: 5
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  port: 5432
